<a href="https://colab.research.google.com/github/clraghuram/tensor-flow-learning/blob/main/TensorFlowLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print('Using Tensor flow version', tf.__version__)

Using Tensor flow version 2.8.2


tf.__version__
In case another version is present,uninstall the current version and reinstall version 2.2.0

pip uninstall tensorflow

pip install tensorflow==2.2.0


In [3]:
vector_tf = tf.constant([0,1,2,3,4])

vector_np = np.array([0,1,2,3,4])

print("Shapes", vector_tf.shape, vector_np.shape)

Shapes (5,) (5,)


In [4]:
# 2-d
t2_tf = tf.constant([[0,1],[2,3],[4,5]]*5)

t2_np = np.array([[0,1],[2,3],[4,5]]*5)

print("Shapes", t2_tf.shape, t2_np.shape)

Shapes (15, 2) (15, 2)


In [5]:
# 3-d
t3_tf = tf.constant([[[0,1],[2,3],[4,5]]]*5)

t3_np = np.array([[[0,1],[2,3],[4,5]]]*5)

print("Shapes", t3_tf.shape, t3_np.shape)

Shapes (5, 3, 2) (5, 3, 2)


In [6]:
## Two types of Variable Declarations
const_tensor = tf.constant([[1,2,3],[4,5,6]])
var_tensor = tf.Variable([[1,2,3],[4,5,6]])

In [7]:
t3_tf

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]], dtype=int32)>

In [8]:
var2_tensor = tf.add(var_tensor,var_tensor)

In [9]:
var2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [10]:
x = tf.Variable([list(range(5))]*5)
y =  tf.Variable([list(range(5,10))]*5)

In [ ]:
z = x+y

print(z)

In [ ]:
w = x*y

print(w)

In [ ]:
v = y/x

print(v)